spring:
  application:
    name: ssoss-backend
  profiles:
    default: local
logging:
  level:
    org.zalando.logbook: TRACE
logbook:
  format:
    style: http
  write:
    max-body-size: 2000
scalar:
  enabled: true
  path: /scalar

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
springdoc:
  api-docs:
    enabled: false
scalar:
  enabled: false
