ALTER TABLE member
    MODIFY COLUMN status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '회원 상태 (PENDING/ACTIVE/WITHDRAWN)',
    ADD COLUMN withdrawn_at DATETIME(6) NULL COMMENT '마지막 탈퇴 시각' AFTER status;
